#!/usr/bin/env bash
# Installs the virtual environment and the necessary Python packages
# needed for running the document broker web service.
# ALWAYS RUN IN DIRECTORY ROOT AFTER CHECKING OUT FROM GIT!

if [ -e ./bin/activate ]
then
    echo "virtual environment already installed"
    exit
fi

# Establish virtualenv

virtualenv .
source bin/activate

# create softlinks
cd document_broker
ln -s ../client &> /dev/null
ln -s ../plugins &> /dev/null

cd ..
cd document_templates
ln -s ../client &> /dev/null
ln -s ../plugins &> /dev/null
cd ..

# Install Django and additional packages

pip install Django

# Install PostgreSL interface. Assume Postgres itself is already installed.
pip install psycopg2

# Install XML-RPC capability
pip install django_xmlrpc

# Install lxml - a requirement for lpod to work
# If this fails, you need to install libxml2-dev and libxslt-dev.
pip install lxml

# PISA and dependencies for PDF generation
pip install pisa
pip install reportlab
pip install html5lib
pip install pil
pip install django-tastypie

# Photologue - note, PIL MUST be reinstalled using the instructions in this
# post: http://ubuntuforums.org/showpost.php?p=10804763&postcount=2 if
# Photologue JPEG support is to work
pip install django-photologue

# PEP8 module for testing purposes. Currently we need v. 1.2
pip install pep8==1.2

# Install lpod 0.9.3 - not available through pip or easy_install.
third_party/install_lpod.sh





