#!/usr/bin/env bash
# Installs the virtual environment and the necessary Python packages
# needed for running the document broker web service.
# NOTE: This script is called from the "install.sh" script.

# Simple error function

if [ -e ./bin/activate ]
then
    echo "virtual environment already installed" 1>&2
    exit
fi

# Establish virtualenv

virtualenv .
source bin/activate

# create softlinks
cd document_broker
ln -s ../client &> /dev/null
ln -s ../plugins &> /dev/null

cd ..
cd document_templates
ln -s ../client &> /dev/null
ln -s ../plugins &> /dev/null
cd ..

# Install Django and additional packages

PIP_PACKAGES=( Django psycopg2 django_xmlrpc lxml pisa reportlab html5lib pil
django-tastypie  django-photologue pep8==1.2 )


for  package in "${PIP_PACKAGES[@]}"
do
    pip install $package

    RETVAL=$?
    if [ $RETVAL -ne 0 ]; then
        echo "" 1>&2
        echo "ERROR: Unable to install Python package <$package>." 1>&2
        echo -n "Please check your network connection. " 1>&2
        echo "A remote server may be down - please retry later. " 1>&2
        echo "" 1>&2
        exit -1
    fi
done

# Install lpod 0.9.3 - not available through pip or easy_install.
third_party/install_lpod.sh





